### PR TITLE
First review

### PR DESCRIPTION
**Pull request by fabiendv**
I updated the signal's message to remove the polling interval from the popup message (it is already available in the configuration). I updated `applyConfig()` to set up the polling interval in this function instead of `run()`.
I also changed the signal's effect `BREATHE` to `BLINK`. We prefer to use the `BREATHE` effect for errors.

I would suggest to change the applet's name to "Coinbase" and update the [logo](https://www.coinbase.com/press).

I would suggest the following improvements in `package.json` before the release:

- Cut the first question into two: 
1. a drop-down for the 14 cryptocurrencies available on [Coinbase](https://www.coinbase.com/price)
2. a search for the all currencies available on Coinbase. You can get the list with this [link](https://api.coinbase.com/v2/currencies) and find how to do it on [daskeyboard-applet--weather-international](https://github.com/daskeyboard/daskeyboard-applet--weather-international).
With that, you will be able to build your current currency key by adding "-" between these two values.

- Replace the others questions types (for the keys decimals, refresh, and threshold) with a drop-down. This way it improves the user-experience and reduces the possible syntax errors. (examples: decimals key and threshold key can allow the value between 1 and 5, and refresh key can allow the value 1,5,10,20,30,40,50,60)

You can find how to build drop-down lists in our [documentation](https://www.daskeyboard.io/applet-development/user-questions/).

Let me know if you need anything,

### CODE REVIEW

**Comment by Wolfe1** [comment]
@fabiendv Thanks for the suggestions, I will take a look at these when I can and make the necessary changes. 

As for the Breathe vs Blink effect is that a definite rule here? If so where is it documented? I personally find the Blink effect to be more intense than I would like to display.

**Comment by fabiendv** [comment]
It is not a definite rule. The behavior for a signal error effect is to breathe, whereas a notification/alert message is to blink. 
What you can do is to allow the user to select the effect during the configuration. With this way, the users are not stuck. You can put the breathe effect like the default value of your applet. You can find the documentation [here](https://www.daskeyboard.io/applet-development/user-questions/).

Hope this helps,

**Comment by fabiendv** [comment]
I will deploy this version v1.0.0 into the Q software.
May you accept the pull request and create a tag v1.0.0 on your repository?

For the recommendations, you can keep in mind for further development (v2.0.0 because of the new configuration needed). You can forget the idea to change the name and the logo.

**Comment by Wolfe1** [comment]
Done, I will get to the changes sometime next week if I can. Thanks!

**Pull request merged**
